"""initial schema

Revision ID: dad3640cb3fa
Revises: 
Create Date: 2026-10-05 01:24:28.948151

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'dad3640cb3fa'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
